# -*- coding: utf-8 -*-
"""Graduation Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDvdgv7LoeOtxetD8XNh67XWRDbzmqwy
"""

!apt-get update
!apt-get install -y mysql-server
!service mysql start

!mysql -e "CREATE DATABASE IF NOT EXISTS ECommerceDB;"
!mysql -e "CREATE USER IF NOT EXISTS 'colab_user'@'localhost' IDENTIFIED BY 'colab_pass';"
!mysql -e "GRANT ALL PRIVILEGES ON ECommerceDB.* TO 'colab_user'@'localhost';"
!mysql -e "FLUSH PRIVILEGES;"

print("MySQL database set up in Colab!")

import subprocess

with open('Last script updated!.txt', 'r') as file:
    sql_commands = file.read()

commands = [cmd.strip() for cmd in sql_commands.split(';') if cmd.strip()]

print(f"Found {len(commands)} SQL commands to execute")

for i, cmd in enumerate(commands, 1):
    try:
        if not cmd:
            continue

        if cmd.strip().upper().startswith('SELECT'):
            print(f"⚠️ Skipping SELECT statement (command {i})")
            continue

        result = subprocess.run(
            f'mysql -u colab_user -pcolab_pass ECommerceDB -e "{cmd}"',
            shell=True,
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            print(f"✅ Command {i} executed successfully")
        else:
            print(f"⚠️ Command {i} had issues: {result.stderr[:100]}")

    except Exception as e:
        print(f"❌ Error in command {i}: {str(e)[:100]}")

print("\n Database setup complete! Your tables are now ready.")

!pip install mysql-connector-python pandas matplotlib seaborn numpy

print("✅ Libraries installed successfully!")

import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('mysql+mysqlconnector://colab_user:colab_pass@localhost/ECommerceDB')

tables = pd.read_sql("SHOW TABLES", engine)

for table_name in tables.iloc[:, 0]:
    print(f"\n--- Sample from Table: {table_name} ---")
    try:
        sample_df = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5", engine)
        display(sample_df)
        count_df = pd.read_sql(f"SELECT COUNT(*) as cnt FROM {table_name}", engine)
        print(f"Total rows: {count_df['cnt'].iloc[0]:,}")
    except Exception as e:
        print(f"Could not load data for {table_name}: {e}")

import pandas as pd
import numpy as np
import mysql.connector
import matplotlib.pyplot as plt

engine = create_engine('mysql+mysqlconnector://colab_user:colab_pass@localhost/ECommerceDB')

print("Loading Orders data...")
orders = pd.read_sql("SELECT * FROM Orders", engine)
display(orders.head())

print("Loading OrderDetails data...")
order_details = pd.read_sql("SELECT * FROM OrderDetails", engine)
display(order_details.head())

print("Loading Products data...")
products = pd.read_sql("SELECT * FROM Products", engine)
display(products.head())

print("Loading Categories data...")
categories = pd.read_sql("SELECT * FROM Categories", engine)
display(categories.head())

print("Loading Calendar data...")
calendar = pd.read_sql("SELECT * FROM Calendar", engine)
display(calendar.head())

orders['TotalAmount'] = orders['TotalAmount'].astype(float)
order_details['Quantity'] = order_details['Quantity'].astype(int)

merged = order_details.merge(products, on='ProductID') \
                     .merge(categories, on='CategoryID') \
                     .merge(orders, on='OrderID') \
                     .merge(calendar, on='DateID')
merged['Sales'] = merged['Quantity'] * merged['UnitPrice']

print(f"Cleaned data: {len(merged)} rows")
display(merged.head())

print("CREATING PIVOT TABLE: Total Sales per Category per Month")
pivot = pd.pivot_table(
    data=merged,
    values='Sales',
    index='CategoryName',
    columns=['Year', 'Month'],
    aggfunc='sum',
    fill_value=0
)

print("Pivot Table Created!")
print(f"\nShape: {pivot.shape} (Categories × Months)")

print("\n" + "="*60)
print("PIVOT TABLE: Total +Sales per Category per Month")
print("="*60)
display(pivot)

df = merged

df['Segment'] = pd.qcut(df.groupby('CustomerID')['Sales'].transform('sum'),
                        q=3,
                        labels=['Low', 'Medium', 'High'])

result = df.groupby('Segment', observed=False)['Sales'].mean().round(2)

print("Average Order Value by Customer Segment:")
display(result)

crosstab = pd.crosstab(
    index=merged['DayOfWeek'],
    columns=merged['CategoryName'],
    margins=True
)

print("Order Frequency by Day of Week and Product Category")
print("=" * 60)
display(crosstab)

crosstab.to_csv('order_frequency_crosstab.csv')
print("\n Saved to 'order_frequency_crosstab.csv'")

merged['Date'] = pd.to_datetime(merged['Date'])
monthly_sales = merged.groupby(pd.Grouper(key='Date', freq='ME'))['Sales'].sum()

plt.figure(figsize=(10, 6))
plt.plot(monthly_sales.index, monthly_sales.values, marker='o', linewidth=2)

plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Sales Amount ($)')
plt.grid(True, alpha=0.3)

plt.show()

merged = order_details.merge(orders, on='OrderID', how='left')

merged = merged.merge(customers, on='CustomerID', how='left')

print(f"Merged data: {len(merged)} rows")
display(merged.head())

df = order_details.merge(products[['ProductID', 'CategoryID']], on='ProductID') \
                 .merge(categories[['CategoryID', 'CategoryName']], on='CategoryID')

df['Sales'] = df['Quantity'] * df['UnitPrice']

sales_by_cat = df.groupby('CategoryName')['Sales'].sum().sort_values()

sales_by_cat.plot(kind='barh', figsize=(10,6), title='Top Categories', color='lightpink')
plt.show()

product_sales = merged.groupby('ProductName')['Sales'].sum().sort_values(ascending=False)

top_10 = product_sales.head(10)

plt.figure(figsize=(12, 6))
top_10.sort_values().plot(kind='barh', color='darkgreen')

plt.title('Top 10 Products by Sales Volume', fontsize=14, fontweight='bold')
plt.xlabel('Total Sales ($)')

plt.tight_layout()
plt.show()

monthly_sales = (order_details
                 .merge(orders[['OrderID', 'DateID']], on='OrderID')
                 .merge(calendar[['DateID', 'Date']], on='DateID')
                )

monthly_sales['Sales'] = monthly_sales['Quantity'] * monthly_sales['UnitPrice']
monthly_sales['Date'] = pd.to_datetime(monthly_sales['Date'])
my_colors= ['darkgrey','lightyellow','lightgrey','black']

sales_by_month = monthly_sales.groupby(monthly_sales['Date'].dt.strftime('%B %Y'))['Sales'].sum()

sales_by_month.plot.pie(figsize=(10,8), autopct='%1.1f%%', wedgeprops=dict(width=0.3), colors= my_colors)
plt.title('Monthly Sales')
plt.ylabel('')
plt.show()

